### ISSUE TITLE
Flow diagnostics does not build on VS 2019

### ISSUE THREAD

**Issue by lindkvis** [OPM/opm-flowdiagnostics#43]
This is because of a missing include of `<stdexcept>` which is required for `std::runtime_error` according to the standard but is accepted by just about every compiler except VS 2019. The fix is to include `<stdexcept>`, which should be acceptable for all platforms.
```
1>C:\Users\lindkvis\Projects\ResInsight\ThirdParty\custom-opm-flowdiagnostics\opm-flowdiagnostics\opm\flowdiagnostics\DerivedQuantities.cpp(97,24): error C2039: 'runtime_error': is not a member of 'std'
```
It is the correct header for `std::runtime_error`:
![bilde](https://user-images.githubusercontent.com/1160606/69633927-72a47f80-1051-11ea-84c5-f3af73123bd0.png)

**Comment by bska** [comment]
Fixed in #44.
